export const users = [
  {
    name: 'Admin User',
    email: 'admin@shopez.com',
    password: 'admin123',
    isAdmin: true,
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
    isAdmin: false,
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'password123',
    isAdmin: false,
  },
];

export const products = [
  {
    name: 'Wireless Bluetooth Headphones',
    image: '/images/headphones.jpg',
    brand: 'SoundMax',
    category: 'Electronics',
    description:
      'Premium over-ear wireless headphones with active noise cancellation, 30-hour battery life, and rich bass response. Perfect for travel, work, and everyday listening.',
    price: 79.99,
    countInStock: 25,
    rating: 4.5,
    numReviews: 12,
    featured: true,
  },
  {
    name: 'Smart Fitness Watch',
    image: '/images/smartwatch.jpg',
    brand: 'FitTrack',
    category: 'Electronics',
    description:
      'Track your steps, heart rate, sleep, and workouts with this sleek fitness watch. Water-resistant with a 7-day battery life and smartphone notifications.',
    price: 129.99,
    countInStock: 18,
    rating: 4.2,
    numReviews: 8,
    featured: true,
  },
  {
    name: 'Mechanical Gaming Keyboard',
    image: '/images/keyboard.jpg',
    brand: 'KeyPro',
    category: 'Electronics',
    description:
      'RGB backlit mechanical keyboard with blue switches, anti-ghosting technology, and durable aluminum frame built for gamers and typists alike.',
    price: 59.99,
    countInStock: 30,
    rating: 4.7,
    numReviews: 20,
    featured: false,
  },
  {
    name: '4K Ultra HD Action Camera',
    image: '/images/camera.jpg',
    brand: 'ActionCam',
    category: 'Electronics',
    description:
      'Capture stunning 4K footage with this waterproof action camera. Includes a mounting kit, remote control, and image stabilization.',
    price: 149.99,
    countInStock: 10,
    rating: 4.0,
    numReviews: 6,
    featured: false,
  },
  {
    name: "Men's Running Shoes",
    image: '/images/running-shoes.jpg',
    brand: 'StrideFit',
    category: 'Clothing',
    description:
      'Lightweight breathable running shoes with responsive cushioning, designed for long-distance comfort and everyday training.',
    price: 64.99,
    countInStock: 40,
    rating: 4.3,
    numReviews: 15,
    featured: true,
  },
  {
    name: "Women's Denim Jacket",
    image: '/images/denim-jacket.jpg',
    brand: 'UrbanThread',
    category: 'Clothing',
    description:
      'A classic denim jacket with a modern slim fit, perfect for layering across all seasons. Made from durable, breathable cotton denim.',
    price: 49.99,
    countInStock: 22,
    rating: 4.1,
    numReviews: 9,
    featured: false,
  },
  {
    name: 'Stainless Steel Cookware Set',
    image: '/images/cookware.jpg',
    brand: 'ChefLine',
    category: 'Home & Kitchen',
    description:
      '10-piece stainless steel cookware set including pots, pans, and lids. Oven safe, dishwasher safe, and induction compatible.',
    price: 189.99,
    countInStock: 12,
    rating: 4.6,
    numReviews: 11,
    featured: true,
  },
  {
    name: 'Automatic Espresso Machine',
    image: '/images/espresso-machine.jpg',
    brand: 'BrewMaster',
    category: 'Home & Kitchen',
    description:
      'Barista-quality espresso at home with this fully automatic machine featuring a built-in grinder, milk frother, and programmable settings.',
    price: 349.99,
    countInStock: 6,
    rating: 4.8,
    numReviews: 14,
    featured: true,
  },
  {
    name: 'Yoga Mat with Carry Strap',
    image: '/images/yoga-mat.jpg',
    brand: 'ZenFit',
    category: 'Sports & Outdoors',
    description:
      'Extra-thick non-slip yoga mat made from eco-friendly TPE material. Includes a carry strap for easy transport to the gym or studio.',
    price: 24.99,
    countInStock: 50,
    rating: 4.4,
    numReviews: 18,
    featured: false,
  },
  {
    name: 'Adjustable Dumbbell Set',
    image: '/images/dumbbells.jpg',
    brand: 'IronCore',
    category: 'Sports & Outdoors',
    description:
      'Space-saving adjustable dumbbells ranging from 5 to 52.5 lbs per dumbbell. Ideal for home gyms and strength training routines.',
    price: 299.99,
    countInStock: 8,
    rating: 4.6,
    numReviews: 7,
    featured: false,
  },
  {
    name: 'Best-Selling Fiction Novel',
    image: '/images/novel.jpg',
    brand: 'PagePress',
    category: 'Books',
    description:
      'An award-winning fiction novel that has topped bestseller charts worldwide. A gripping story of mystery, love, and redemption.',
    price: 14.99,
    countInStock: 60,
    rating: 4.9,
    numReviews: 32,
    featured: true,
  },
  {
    name: 'Kids Educational Building Blocks',
    image: '/images/building-blocks.jpg',
    brand: 'BrainyBlocks',
    category: 'Toys',
    description:
      '200-piece educational building block set that encourages creativity, problem-solving, and fine motor skills in children ages 3+.',
    price: 34.99,
    countInStock: 35,
    rating: 4.5,
    numReviews: 10,
    featured: false,
  },
];
